name: CI
on:
  push:
    branches:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/set-up@v2
      with:
        version: 7
    - run: chmod +x ./ci.sh && ./ci.sh
      shell: bash
